services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nerootxon
    ports:
      - 27017:27017
    volumes:
      - mongo-data-test:/data/db
    container_name: mongo-db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: nerootxon
      ME_CONFIG_MONGODB_URL: mongodb://root:nerootxon@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    container_name: mongo-test

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    environment:
      MONGO_URI: mongodb://root:nerootxon@mongo:27017/
      JWT_SECRET: asdfasdf
    container_name: auth-test

volumes:
  mongo-data-test:
